version: "3.8"
services:
  python-script-scheduler:
    container_name: python-script-scheduler
    build:
      context: .
    volumes:
      - ./crontab:/etc/cron.d/python-scheduler
      - ./scripts:/app/scripts